nav:
  Home: /
  About: /about/
  Writing: /archives/
  Projects: http://github.com/austionian

projects_url: http://github.com/austionian

customize:
    gravatar:
        email:
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/pip-head.png
        gravatar: false
    favicon:
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/pip-head.png
        gravatar: false
      android:
        url: /images/pip-head.png
        gravator: false
      apple:
        url: /images/pip-eight.png
        gravator: false
    social_links:
        github: http://github.com/austionian
        twitter: https://twitter.com/austin_rooks
        linkedin: https://www.linkedin.com/in/austinrooks/
    show_all_posts: false
    post_count: 5
    highlight: rainbow

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-86660611-1 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
